## <b>Problem 1</b>

If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

* Find the sum of all the multiples of 3 or 5 below 1000.

In [42]:
mult = [x for x in range(1000) if (x%3==0 or x%5==0) and x!=0]

In [43]:
sum(mult)

233168

## <b>Problem 2</b>
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

<center>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</center>
<br>

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

In [1]:
def fib(x):
    if x<2:
        return 1
    if x>=2:
        return fib(x-1) + fib(x-2)

In [16]:
i = 0
a = 0
while True :
    a = fib(i)
    if a>4e6:
        break
    else:
        i += 1
print(i)

33

In [22]:
l1 = [fib(x) for x in range(33)]
fib_less = list(enumerate(l1))

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578]

In [23]:
fib_less

[(0, 1),
 (1, 1),
 (2, 2),
 (3, 3),
 (4, 5),
 (5, 8),
 (6, 13),
 (7, 21),
 (8, 34),
 (9, 55),
 (10, 89),
 (11, 144),
 (12, 233),
 (13, 377),
 (14, 610),
 (15, 987),
 (16, 1597),
 (17, 2584),
 (18, 4181),
 (19, 6765),
 (20, 10946),
 (21, 17711),
 (22, 28657),
 (23, 46368),
 (24, 75025),
 (25, 121393),
 (26, 196418),
 (27, 317811),
 (28, 514229),
 (29, 832040),
 (30, 1346269),
 (31, 2178309),
 (32, 3524578)]

In [25]:
even_index = [3*x-1 for x in range(33) if 3*x-1 > 0 and 3*x-1<=32]
even_index

[2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32]

In [30]:
sum_even = 0
for i, j in fib_less:
    if i in even_index:
        sum_even += j

In [31]:
sum_even

4613732

## <b>Problem 3</b>
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

In [1]:
def is_prime(n):
    for i in range(2,n):
        if n%i == 0:
            return False
        else:
            pass
    return True

In [ ]:
prime_list = [x for x in range(int()) if is_prime(x)]

In [2]:
import numpy as np

In [8]:
1e9

1000000000.0

In [11]:
1e9/np.log(10)*9 + np.log(6.01)

3908650338.9226904

In [10]:
1e10/np.log(10)*9 + np.log(6.01)

39086503373.08608

## <b>Problem 4</b>

A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 Ã— 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [1]:
def is_palindrome(number):
    num = str(number)
    lenght = len(num)
    if lenght == 1:
        return False
    if lenght%2 == 0:
        case = lenght
    else:
        case = lenght - 1 
    ls = list(enumerate([-1-x for x in range(int(case/2))]))

    phrase = [f'num[{i}] == num[{j}]' for i,j in ls]
    expression = " and ".join(phrase)
    
    if eval(expression):
        return True
    else: 
        return False

In [2]:
999**2

998001

In [3]:
palindromes  = [x for x in range(10000,998002) if is_palindrome(x)]

In [7]:
for t in palindromes[::-1]:
    if is_threedigit(factors(t)):
        print(t)
        break
    else:
        pass

906609

In [5]:
def factors(n):
    fac = list()
    for i in range(1,n):
        if n%i == 0:
            if not (((i,int(n/i)) in fac) or ((int(n/i)),i) in fac):
                fac.append((i,int(n/i)))
    return fac

In [6]:
def is_threedigit(list_factors):
    for i,j in list_factors:
        if len(str(i)) == 3 and len(str(j)) == 3:
            return True
        else:
            pass
    return False

In [8]:
factors(906609)

[(1, 906609),
 (3, 302203),
 (11, 82419),
 (33, 27473),
 (83, 10923),
 (249, 3641),
 (331, 2739),
 (913, 993)]

In [105]:
ls = [(x * y) 
      for x in range(100,110)
      for y in range(100,110)]

In [ ]:
from os import